export const deviceTypes = {
    ADD_REQUEST: 'DEVICE_ADD_REQUEST',
    ADD_SUCCESS: 'DEVICE_ADD_SUCCESS',
    ADD_FAILURE: 'DEVICE_ADD_FAILURE',

    FILTER: 'DEVICE_FILTER',

    INDEX_REQUEST: 'DEVICE_INDEX_REQUEST',
    INDEX_SUCCESS: 'DEVICE_INDEX_SUCCESS',
    INDEX_FAILURE: 'DEVICE_INDEX_FAILURE',

    SELECT: 'DEVICE_SELECT',

    SHOW_REQUEST: 'DEVICE_SHOW_REQUEST',
    SHOW_SUCCESS: 'DEVICE_SHOW_SUCCESS',
    SHOW_FAILURE: 'DEVICE_SHOW_FAILURE',

    UPDATE_STATUS_REQUEST: 'DEVICE_UPDATE_STATUS_REQUEST',
    UPDATE_STATUS_SUCCESS: 'DEVICE_UPDATE_STATUS_SUCCESS',
    UPDATE_STATUS_FAILURE: 'DEVICE_UPDATE_STATUS_FAILURE',
};