export const userTypes = {
    ADD_REQUEST: 'USER_REGISTER_REQUEST',
    ADD_SUCCESS: 'USER_REGISTER_SUCCESS',
    ADD_FAILURE: 'USER_REGISTER_FAILURE',

    GET_REQUEST: 'USER_GET_REQUEST',
    GET_SUCCESS: 'USER_GET_SUCCESS',
    GET_FAILURE: 'USER_GET_FAILURE',
    
    UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
    
    DELETE_REQUEST: 'USER_DELETE_REQUEST',
    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE',
    
    EDIT_REQUEST: 'USER_EDIT_REQUEST',
    EDIT_SUCCESS: 'USER_EDIT_SUCCESS',
    EDIT_FAILURE: 'USER_EDIT_FAILURE',
};